import { useState, useEffect } from 'react';
import Head from 'next/head';
import Table from '../components/table/table';
import TodoList from '../components/todoList/todoList';

export default function Home() {
  const [users, setUsers] = useState([]);
  const [todoList, setTodoList] = useState([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);
  const [searchtext, setSearchText] = useState('');

  useEffect(() => {
    fetch('https://jsonplaceholder.typicode.com/users')
      .then((res) => res.json())
      .then((data) => {
        setIsLoading(true);
        setUsers(data);
      });
    (error) => {
      setIsLoading(false);
    };
  }, []);

  const searchByNameOrEmail = (data) => {
    return users.filter((user) => {
      const { name, email } = user;
      if (
        name.toLowerCase().includes(searchtext) ||
        email.toLowerCase().includes(searchtext)
      ) {
        return user;
      }
    });
  };

  const fetchTodoList = (userId) => {
    console.log(userId);
    fetch(`https://jsonplaceholder.typicode.com/todos?userId=${userId}`)
      .then((res) => res.json())
      .then((data) => {
        setIsLoading(true);
        setTodoList(data);
      });
  };

  const handleTodo = (id) => {
    // console.log(id);
    const list = todoList.map((todo) => {
      if (id === todo.id) {
        if (todo.completed) {
          todo.completed = false;
        } else {
          todo.completed = true;
        }
      }
      return { ...todo };
    });
    // console.log(toggle);
    setTodoList(list);
  };

  const removeTodo = (id) => {
    const list = todoList.filter((todo) => {
      if (id !== todo.id) {
        return { ...todo };
      }
    });
    return setTodoList(list);
  };

  const filterByDomain = (e) => {
    //console.log(e.target.value);
    // const { value } = e.target;
    // const filteredUser = users.filter((user) => {
    //   const { website } = user;
    //   if (website.includes(value)) {
    //     return user;
    //   }
    // });
    // console.log(filterUser);
  };

  return (
    <div>
      <Head>
        <title>ORX Assessment</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div className='w-full p-5'>
          <div className='w-full flex flex-row'>
            <div className='w-1/2'>
              <label>Search by name or email:</label>
              <input
                className='p-3 inline-block border-[1px] rounded box-border'
                type='text'
                onChange={(e) => setSearchText(e.target.value)}
              />
            </div>
            <div className='w-1/2'>
              <label>Filter by Domain:</label>
              <div className='flex flex-col justify-start'>
                <div>
                  <input
                    className='m-3'
                    type='checkbox'
                    name='Net'
                    id='net'
                    value='net'
                    onChange={(e) => filterByDomain(e)}
                  />
                  <label>Net</label>
                </div>
                <div>
                  <input
                    className='m-3'
                    type='checkbox'
                    name='Com'
                    id='com'
                    value='com'
                    onChange={(e) => filterByDomain(e)}
                  />
                  <label>Com</label>
                </div>
                <div>
                  <input
                    className='m-3'
                    type='checkbox'
                    name='Others'
                    id='others'
                    value='others'
                    onChange={(e) => filterByDomain(e)}
                  />
                  <label>Others</label>
                </div>
              </div>
            </div>
          </div>
          <Table
            data={searchByNameOrEmail(users)}
            fetchTodoList={fetchTodoList}
          />

          <h1 className='mt-8 text-7xl text-center'>TodoList</h1>
          <TodoList
            todoList={todoList}
            handleTodo={handleTodo}
            removeTodo={removeTodo}
          />
        </div>
      </main>
    </div>
  );
}
